name: F# CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: Lab2.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore project
      run: dotnet restore .\Fsharp\Fsharp.fsproj

    - name: Install linter
      run: dotnet tool install dotnet-fsharplint --version 0.21.6
    - name: Run linter
      run: dotnet fsharplint lint --file-type project .\Lab2\Lab2.fsproj

    - name: Install formatter
      run: dotnet tool install fantomas
    - name: Run formatter
      run: dotnet fantomas --check ./Lab2

    - name: Run tests
      run: dotnet test
